### ISSUE TITLE
Error in 'me/picture'

### ISSUE THREAD

**Issue by avelino** [jgorset/facepy#119]
(Pdb) graph.get('me/picture')
**\* UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by crazyscorpio12** [comment]
I am getting the same error again on 
```
graph.get(path='me/picture')

UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
``` 
The fix implemented, no longer exists in the latest release 1.0.6

**Comment by crazyscorpio12** [comment]
nevermind, adding ?redirect=false returns the URL

**Comment by sashabaranov** [comment]
Still get this with 1.08
