### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by archey** [jgorset/facepy#125]
File "setup.py", line 1
    rom setuptools import setup

Looks like from is misspelled in the setup.py, you might want to change it and do a quick release.

This is on the latest 1.0.6 release.

**Comment by jgorset** [comment]
Damn, you're fast! I force pushed that like two minutes later. ;-)

**Comment by archey** [comment]
DId you happen to push a new git tag as the 1.0.6 release still seems to have the typo, in it?

**Comment by jgorset** [comment]
Ah! I must not have force pushed that. Thank you.
