### ISSUE TITLE
Random OAuthErrors

### ISSUE THREAD

**Issue by tkazec** [jgorset/facepy#127]
We've been getting this error occasionally in a crawler script that runs every 15 minutes:

    facepy.exceptions.OAuthError: [2] An unexpected error has occurred. Please retry your request later.

Happens every week or so, in clusters of several failures on a single day. Not sure where to start looking to fix it.

**Comment by jgorset** [comment]
Don't — pretty sure this is something that only Facebook can look into. :-)

**Comment by tkazec** [comment]
Gotcha. Is there any way facepy can provide more information in the exception?

**Comment by jgorset** [comment]
I think that's all Facebook says! It used to be, anyway, but if you can confirm that with your error that'd be neat.

**Comment by tkazec** [comment]
Looks to be that way. Thanks anyway!
