### ISSUE TITLE
Send private messages through the Graph API

### ISSUE THREAD

**Issue by astinx** [jgorset/facepy#128]
Hi there! I wanna know if the library offers some support to send private messages through the Graph API. I researched a little bit and I found that there's some ways to achieve this, if the library doesn't have any support for this I could make a fork and add this feature :P

**Comment by astinx** [comment]
Sorry I researched further and I realized that is impossible to do it only through the Graph API, closing issue.

**Comment by jgorset** [comment]
No worries @astinx!
