### ISSUE TITLE
Not able to fetch paginated data from facebook

### ISSUE THREAD

**Issue by shobhitmittal** [jgorset/facepy#129]
from facepy import GraphAPI
import json

access = 'CAACEdEose0cBAAoduuLZAahA.................WTIpfI69bEiyN'

graph = GraphAPI(access)
page_id= '359097957437099'
data= graph.get(page_id, page=True, retry=5, fields='posts{id}')

for i in data:
	json_data=json.dumps(i, separators=(',',':'))
	print json_data

I am not able to fetch paginated data from facebook, Please resolve, M using facepy(1.0.6)

**Comment by jgorset** [comment]
The Graph API doesn't seem to get pagination right when you're querying the page and asking for posts in the `fields` parameter, but it works fine if I instead query `/posts`:

```python
data = graph.get('359097957437099/posts', fields='id', page=True)
for i in data:
    print data
```
