### ISSUE TITLE
Page insights suddenly stopped working (May be due to API version change)

### ISSUE THREAD

**Issue by sibiyes** [jgorset/facepy#131]
Hi,

I have been using facepy for awhile to pull insight metrics for pages through Apps.

Things have been working well and it suddenly stopped working today (April 30, 2015) and returns an empty array.

My call looks like this

pageGraph = GraphAPI(pageAccess)
extract = pageGraph.get(postId + '/insights')

Given the timing of the issue I think the Graph API version change could be the reason.

The posts end point still seems to work.

pageGraph = GraphAPI(pageAccess)
extract = pageGraph.get('me/posts', page = True) 

So I was wondering if the endpoint for insights still exists or has it been moved to some other end point

Thanks

Sibi

**Comment by sibiyes** [comment]
It got fixed by itself. Most likely an issue at Facebook's end. Probably a migration of API version

**Comment by jgorset** [comment]
Alright, good to hear!
