### ISSUE TITLE
Post Videos

### ISSUE THREAD

**Issue by Azrrael-exe** [jgorset/facepy#132]
I have been trying to post videos using FacePy, but according with the Grap Api documentation the video must be encoding as form data.

I am trying to make a function to encode the file, but I am non an expert.

There are any tip to make it work?

Thanks!

**Comment by Azrrael-exe** [comment]
I just need to specify the path 7me/videos/: Fixed!

**Comment by mdublin** [comment]
@Azrrael-exe Hi there, if you're looking for a simpler alternative for uploading videos via Facebook's Graph Video API, I just uploaded this script here: 

https://github.com/mdublin/Facebook-Video-Uploader
