### ISSUE TITLE
OAuthError: [2500] An active access token must be used to query information about the current user

### ISSUE THREAD

**Issue by NinshuBird** [jgorset/facepy#135]
I am getting the token using 

https://graph.facebook.com/oauth/access_token?client_id=xxxxx&client_secret=xxxxx&grant_type=client_credentials&scope=user_friends

Thanks for reading

**Comment by jgorset** [comment]
That's an Application Access Token. To query `me` from the Graph API, you need an User Access Token. You can read more about access tokens [here](https://developers.facebook.com/docs/facebook-login/access-tokens#usertokens).
