### ISSUE TITLE
GraphAPI.batch should accept generators as well as fixed-length lists

### ISSUE THREAD

**Issue by brownstein** [jgorset/facepy#136]
Got this from feeding the batch method a generator:
>
 File "/usr/local/lib/python2.7/site-packages/facepy/graph_api.py", line 181, in batch
    for group in _grouper(requests, 50):
  File "/usr/local/lib/python2.7/site-packages/facepy/graph_api.py", line 174, in _grouper
    for i in range(0, len(complete_list), n):
TypeError: object of type 'generator' has no len()

I get that this method is intended for lists, but I'd like it to accept generators for batch processing applications. PR to follow.

**Comment by jgorset** [comment]
Thanks for the pull request! I'll close this issue.
