### ISSUE TITLE
pagination raises `facepy.exceptions.OAuthError`

### ISSUE THREAD

**Issue by swizzard** [jgorset/facepy#141]
Facepy raises `facepy.exceptions.OAuthError` instead of `StopIteration` when using `GraphAPI.get` with `pagination=True`.

On the one hand, this is unhelpful/alarming for users. On the other, I'm not sure there's any actual way for facepy to differentiate between 'no more pages' and 'this link is broken for other reasons'.

**Comment by swizzard** [comment]
Reopening with slightly more information: this appears to be tied to platforms/builds without a "true SSLContext object", such as AWS EC2 instances--this bug surfaces there, but not on my local machine.

**Comment by jgorset** [comment]
Wait, what? Why? That doesn't make sense to me.
