### ISSUE TITLE
How to Use Signed Request?

### ISSUE THREAD

**Issue by vionemc** [jgorset/facepy#142]
Hi, I am confused how to use Signed Request.
Currently, I use it like this:
`SignedRequest('http://graph.facebook.com/me', my_access_token)`

And I got this response: `facepy.exceptions.SignedRequestError: Signed request had a corrupt payload`

Any help would be appreciated :D

**Comment by jgorset** [comment]
Please see the [documentation on `SignedRequest`](http://facepy.readthedocs.org/en/latest/usage/signed-requests.html).
