### ISSUE TITLE
Adding header to API request

### ISSUE THREAD

**Issue by vionemc** [jgorset/facepy#143]
http://stackoverflow.com/questions/3595518/facebook-graph-api-search-results-depends-on-location

Based on that Q&A, it will be good if we can add header when sending an API request. Like `'Accept-Language: en-us,en;'`. It will affect the result since Facebook automatically detect the requester location.

I think that's a great idea!

**Comment by jgorset** [comment]
Absolutely, @vionemc! Please feel free to submit a pull request if you find the time. There's :cake:. And it's not a lie.

**Comment by saratlingamarla** [comment]
Hi @jgorset and @vionemc ,
I'd like your opinions on my approach:
1. I created a dictionary of all supported locales, Example:{'German' : 'de_DE' .....}
Users can use the keys to insert their values.

2.The value of the key from the selected language is inserted as header 
3.I would change the _query method in graph_api.py to accept headers

Would that suffice?

**Comment by azmainamin** [comment]
Any update on this?

**Comment by jgorset** [comment]
Sorry for going silent on you guys! I just explored the Graph API and it seems that this is no longer needed; search now accepts a query parameter `center` to set the location, and as far as I can tell no other endpoints need custom headers (but please just reopen if I'm wrong about that!)
