### ISSUE TITLE
different results compare with graph API explorer

### ISSUE THREAD

**Issue by nvcken** [jgorset/facepy#145]
I tried to get list of user photos.
Results from facepy missed few photos compare with results which get from Facebook graph API explorer.
I figured out the reason make results different is graph version between 2.3 vs 2.4+
Summary:
- v2.3 : results miss few latest photos
- v2.4+ : get properly full photos

How can I use facepy with latest graph API version

**Comment by swizzard** [comment]
You can pass version as a keyword argument to GraphAPI, e.g.

    graph = GraphAPI(token, version="2.5")

**Comment by jgorset** [comment]
Exactly right, @swizzard. It also defaults to whatever version is the default for your application.
