### ISSUE TITLE
Paginated requests ignore retry param

### ISSUE THREAD

**Issue by kevinjdolan** [jgorset/facepy#147]
When making a paginated request, the try/catch block that performs the retries will never be executed, since the method returns a generator successfully before making any actual requests.

For large paginated requests (like a long history of stats), I have observed on many occasions transient failures that go away with retries, so my expectation would be that the retry count is enforced on a per-page basis, rather than for the entire logical request.

I will contribute a patch later today, as it seems like a rather trivial fix to simply apply two different retry modes without impacting the method signature at all.

**Comment by jgorset** [comment]
> I will contribute a patch later today, as it seems like a rather trivial fix to simply apply two different retry modes without impacting the method signature at all.

My favourite kind of issues. :wink:
