### ISSUE TITLE
fql is deprecated for versions v2.1 and higher error

### ISSUE THREAD

**Issue by bmarchenko** [jgorset/facepy#152]

**Comment by jgorset** [comment]
I'm not sure what you mean by this issue – I'm assuming that you have an application that has been targeting Graph API v2.0 or earlier, but that's [no longer available](https://developers.facebook.com/docs/apps/changelog) and all the calls you're making are now being upgraded to Graph API 2.1.

I removed FQL from 16ebfe39f0778cad2bf164646618fe9a474d141a so there's no confusion.
