### ISSUE TITLE
SignedRequest broken with Python 3

### ISSUE THREAD

**Issue by merwok** [jgorset/facepy#159]
ImportError: No module named 'urlparse'

.../facepy/signed_request.py in fetch_user_data_and_token, line 75

**Comment by merwok** [comment]
@jgorset Can I ask if you intend to make a release with this fix soon, or if you’re waiting for other fixes?

**Comment by jgorset** [comment]
I just released 1.0.9, @merwok. Sorry that it took a while – I had to get things set up on my computer again and so procrastination got the best of me.

**Comment by merwok** [comment]
Super, thanks!
