### ISSUE TITLE
pagination bug

### ISSUE THREAD

**Issue by millerthegorilla** [jgorset/facepy#165]
similar to #126:

At line 279 in graph_api.py:
          
          try:
                next_url = result['paging']['next']
            except (KeyError, TypeError):
                next_url = None

next_url is always none when the results do not have ['paging'] in them.  I replaced it with the following:
          
          try:
                next_url = result['paging'].get('next', None)
           except (KeyError, TypeError):
                next_url = result['posts']['paging'].get('next', None)

This covers situations where the request string contains 'posts'  as in the first page of results, 'posts' is a superordinate dictionary to 'paging' in an request formed like this:

    me?fields=posts.include_hidden(true){created_time,from,message,comments{created_time,from,message,comments{created_time,from,message},attachment},full_picture}
It doesn't cover any situation where there is more complicated request string, although I am uncertain if such a thing could exist, but I put the code in the next comment to cover any situation where that might be the case.

**Comment by millerthegorilla** [comment]
the commented code refers to a recursive function that handles nested dictionaries, which might be useful for some request strings, so perhaps this:

            try:
                next_url = result['paging'].get('next', None)
            except KeyError:
                try:
                    next_url = result['posts']['paging'].get('next', None)
                except KeyError:
                    for page in dict_extract('next', result):
                        if page[:5] == 'https':
                            next_url = page
                            break
                    else:
                        next_url = None
            except TypeError:
                next_url = None

**Comment by jgorset** [comment]
Can't believe it took me a year to get around to this. Sorry @millerthegorilla! It would be a good feature for pagination to work with nested resources like `posts`, too.

**Comment by jgorset** [comment]
I implemented this!
