### ISSUE TITLE
This query works when i try it with https://developers.facebook.com

### ISSUE THREAD

**Issue by cheulong** [jgorset/facepy#168]
posts?fields=comments.since(2018-05-25).until(2018-05-29)

 facepy.exceptions.OAuthError: [2500] Syntax error "Expected end of string instead of "?"." at character 5: posts?fields=comments.since(2018-05-25).until(2018-05-29)

**Comment by jgorset** [comment]
Can't believe I left this one without a reply for over a year. Sorry @cheulong (and hope you found out what was wrong).
