### ISSUE TITLE
uploadAlbum results in error

### ISSUE THREAD

**Issue by kettenbach-it** [jgorset/facepy#171]
Hi,

since 3 days I get this error on uploadAlbum():
```
Request return 400 error!
{'message': 'child_needs_reupload', 'upload_id': '1572503813', 'error_title': '1572503813', 'status': 'fail'}
```

Other "APIs" seem to have problem, too:
https://github.com/mgp25/Instagram-API/issues/2972
https://github.com/mgp25/Instagram-API/issues/2971
https://github.com/timgrossmann/InstaPy/issues/5178

I think instagram has changed something in the API.

**Comment by Ebloom59** [comment]
any news ?

**Comment by jgorset** [comment]
Sorry to be so slow on this. Were you able to resolve this, or are you still having issues? Please feel free to reopen this if you're still having issues and I'll try to help.
